### ISSUE TITLE
Endpoint creation - Part 1

### ISSUE THREAD

**Issue by dobber1611** [msoeSE/TheHopefuls#20]
Part 1 - requesting for user data, driving session data, driving school data

**Comment by zawadzkip** [comment]
Endpoint Ideas:
Endpoint for pulling state statistics (Maybe next sprint since we haven't researched yet)
Saving Driver stats
querying driver stats for user (add parameter for all stats, x amount of stats)


Since this sprint really only has stat related stuff, I don't think it would make sense to add anymore endpoints than these, unless I'm missing something.
